-- MySQL Script generated by MySQL Workbench
-- Seg 12 Jan 2015 21:10:30 BRST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_megaquality
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_megaquality` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_megaquality` ;

-- -----------------------------------------------------
-- Table `db_megaquality`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_megaquality`.`users` ;

CREATE TABLE IF NOT EXISTS `db_megaquality`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_megaquality`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_megaquality`.`items` ;

CREATE TABLE IF NOT EXISTS `db_megaquality`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_megaquality`.`checklists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_megaquality`.`checklists` ;

CREATE TABLE IF NOT EXISTS `db_megaquality`.`checklists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_megaquality`.`stages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_megaquality`.`stages` ;

CREATE TABLE IF NOT EXISTS `db_megaquality`.`stages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_megaquality`.`checklists_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_megaquality`.`checklists_items` ;

CREATE TABLE IF NOT EXISTS `db_megaquality`.`checklists_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `checklist_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_checklists_items_item_idx` (`item_id` ASC),
  INDEX `fk_checklists_items_checklist_idx` (`checklist_id` ASC),
  CONSTRAINT `fk_checklists_items_checklist`
    FOREIGN KEY (`checklist_id`)
    REFERENCES `db_megaquality`.`checklists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checklists_items_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `db_megaquality`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_megaquality`.`stages_checklists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_megaquality`.`stages_checklists` ;

CREATE TABLE IF NOT EXISTS `db_megaquality`.`stages_checklists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stage_id` INT NOT NULL,
  `checklist_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stages_checklists_stage_idx` (`stage_id` ASC),
  INDEX `fk_stages_checklists_checklist_idx` (`checklist_id` ASC),
  CONSTRAINT `fk_stages_checklists_stage`
    FOREIGN KEY (`stage_id`)
    REFERENCES `db_megaquality`.`stages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stages_checklists_checklist`
    FOREIGN KEY (`checklist_id`)
    REFERENCES `db_megaquality`.`checklists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_megaquality`.`auditings_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_megaquality`.`auditings_template` ;

CREATE TABLE IF NOT EXISTS `db_megaquality`.`auditings_template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_megaquality`.`auditings_template_stages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_megaquality`.`auditings_template_stages` ;

CREATE TABLE IF NOT EXISTS `db_megaquality`.`auditings_template_stages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stage_id` INT NOT NULL,
  `auditing_template_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auditings_template_stages_stage_idx` (`stage_id` ASC),
  INDEX `fk_auditings_template_stages_auditing_idx` (`auditing_template_id` ASC),
  CONSTRAINT `fk_auditings_template_stages_auditing`
    FOREIGN KEY (`auditing_template_id`)
    REFERENCES `db_megaquality`.`auditings_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auditings_template_stages_stage`
    FOREIGN KEY (`stage_id`)
    REFERENCES `db_megaquality`.`stages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_megaquality`.`auditings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_megaquality`.`auditings` ;

CREATE TABLE IF NOT EXISTS `db_megaquality`.`auditings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auditing_template_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auditings_auditings_template_idx` (`auditing_template_id` ASC),
  CONSTRAINT `fk_auditings_auditings_template`
    FOREIGN KEY (`auditing_template_id`)
    REFERENCES `db_megaquality`.`auditings_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



/*
 * username = admin
 * password = teste
 */
INSERT INTO `users` (name, username, password) VALUES ("Administrator", "admin", "$2a$10$tR5yZNYznAEmnPRIDtCZrefwKfu1HYfL4Vw3Ccyjh9E7Dezev/yv.");


